import cover from "./images/QuizBackround.svg";
export const QuizData = [
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 12,
  },
  {
    QuizName: "Chemical Reactions",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 10,
  },
  {
    QuizName: "Football Team Quiz",
    cover: cover,
    category: "Sport",
    numberOfQuizzes: 2,
  },
  {
    QuizName: "Tech Innovations",
    cover: cover,
    category: "Tech",
    numberOfQuizzes: 8,
  },
  {
    QuizName: "Classic Novels",
    cover: cover,
    category: "Literature",
    numberOfQuizzes: 5,
  },
  {
    QuizName: "Olympic Games History",
    cover: cover,
    category: "Sport",
    numberOfQuizzes: 5,
  },
  {
    QuizName: "Statistics Math Quiz",
    cover: cover,
    category: "Math",
    numberOfQuizzes: 6,
  },
  {
    QuizName: "Ancient Civilizations ",
    cover: cover,
    category: "History",
    numberOfQuizzes: 3,
  },
  {
    QuizName: "Galaxies and Nebulas",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 4,
  },
  {
    QuizName: "Biology Basics",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 12,
  },
  {
    QuizName: "Evolution Exploration",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 10,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Evolution Exploration",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 10,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 12,
  },
  {
    QuizName: "Chemical Reactions",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 10,
  },
  {
    QuizName: "Football Team Quiz",
    cover: cover,
    category: "Sport",
    numberOfQuizzes: 2,
  },
  {
    QuizName: "Tech Innovations",
    cover: cover,
    category: "Tech",
    numberOfQuizzes: 8,
  },
  {
    QuizName: "Classic Novels",
    cover: cover,
    category: "Literature",
    numberOfQuizzes: 5,
  },
  {
    QuizName: "Olympic Games History",
    cover: cover,
    category: "Sport",
    numberOfQuizzes: 5,
  },
  {
    QuizName: "Statistics Math Quiz",
    cover: cover,
    category: "Math",
    numberOfQuizzes: 6,
  },
  {
    QuizName: "Ancient Civilizations ",
    cover: cover,
    category: "History",
    numberOfQuizzes: 3,
  },
  {
    QuizName: "Galaxies and Nebulas",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 4,
  },
  {
    QuizName: "Biology Basics",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 12,
  },
  {
    QuizName: "Evolution Exploration",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 10,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Evolution Exploration",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 10,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
  {
    QuizName: "Biology Brain Teasers",
    cover: cover,
    category: "Science",
    numberOfQuizzes: 11,
  },
];
