const aze = {
  dashboard: "Ana səhifə",
  discover: "Kəşfet",
  leaderboard: "Liderlik lövhəsi",
  settings: "Tənzimləmələr",
  quizLibrary: "Kuiz Kitabxanası",
  quizPerformance: "Quiz Statistikası",
  recentQuiz: "Son oynanan kuiz",
  ongoingQuiz: "Növbəti quiz",
  seeAll: "Hamısını gör",
  seeLess: "Hamısını görmə",
  weekly: "Həftəlik",
  allTime: "Bütün Dövr",
  other: "Digər",
  lastAddedQuizzes: "Son Əlavə Edilən Quizlər",
  friends: "Dostlar",
  point: "X",
  quizzes: "Kuiz",
  goodMorning: "SABAHINIZ XEYİR",
  goodAfternoon: "GÜNORTANIZ XEYİR",
  goodEvening: "AXŞAMINIZ XEYİR",
  goodNigth: "GECƏNİZ XEYRƏ",
  Categories: "Kateqoriyalar",
  Quiz: "Kuiz",
  ClearAll: "Təmizlə",
  RecentSearchers: "Son Axtarılanlar",
  QuizAndCategories: "Kuiz və kateqoriyalar",
  myAccount: "Hesabım",
  logOut: "Hesabdan Çıx",
  liveQuizText: " Hal-hazırda canlı kuiz yoxdur.",
  liveQuiz: "Canlı Kuiz",
  quizList: "Quiz Siyahısı",
  createQuiz: "Kuiz Yarat",
  findQuizzes: "Kuizləri ada görə tapın",
  Category: "Kateqoriya",
  points: "xal",
  Name: "Ad",
  Country: "Ölkə",
  Rank: "Sıralama",
  Afghanistan: "Əfqanıstan",
  Albania: "Albaniya",
  Algeria: "Əlcəzair",
  Andorra: "Andorra",
  Angola: "Anqola",
  AntiguaAndBarbuda: "Antiqua və Barbuda",
  Argentina: "Argentina",
  Armenia: "Ermənistan",
  Australia: "Avstraliya",
  Austria: "Austriya",
  Azerbaijan: "Azərbaycan",
  Bahamas: "Baham adaları",
  Bahrain: "Bəhreyn",
  Bangladesh: "Banqladeş",
  Barbados: "Barbados",
  Belarus: "Belarus",
  Belgium: "Belçika",
  Belize: "Belize",
  Benin: "Benin",
  Bhutan: "Butan",
  Bolivia: "Boliviya",
  BosniaAndHerzegovina: "Bosniya və Herseqovina",
  Botswana: "Botsvana",
  Brazil: "Brazilya",
  Brunei: "Bruney",
  Bulgaria: "Bulqarıstan",
  BurkinaFaso: "Burkina Faso",
  Burundi: "Burundi",
  CaboVerde: "Kabo Verde",
  Cambodia: "Kamboca",
  Cameroon: "Kamerun",
  Canada: "Kanada",
  CentralAfricanRepublic: "Mərkəzi Afrika Respublikası",
  Chad: "Çad",
  Chile: "Çili",
  China: "Çin",
  Colombia: "Kolombiya",
  Comoros: "Komorlar",
  Congo: "Konqo",
  CostaRica: "Kosta Rica",
  CotedIvoire: "Kot d'İvuar",
  Croatia: "Croatia",
  Cuba: "Xorvatiya",
  Cyprus: "Kıbrıs",
  CzechRepublic: "Çexiya",
  Denmark: "Danimarka",
  Djibouti: "Cibuti",
  Dominica: "Dominika",
  DominicanRepublic: "Dominikan Respublikası",
  Ecuador: "Ekvador",
  Egypt: "Misir",
  ElSalvador: "El Salvador",
  EquatorialGuinea: "Ekvatorial Qvineya",
  Eritrea: "Eritreya",
  Estonia: "Estoniya",
  Eswatini: "Esvatini",
  Ethiopia: "Efiopiya",
  Fiji: "Fici",
  Finland: "Finlandiya",
  France: "Fransa",
  Gabon: "Qabon",
  Gambia: "Qambia",
  Georgia: "Gürcüstan",
  Germany: "Almaniya",
  Ghana: "Qana",
  Greece: "Yunanıstan",
  Grenada: "Qrenada",
  Guatemala: "Qvatemala",
  Guinea: "Qvineya",
  GuineaBissau: "Qvineya-Bisau",
  Guyana: "Qayana",
  Haiti: "Haiti",
  Honduras: "Honduras",
  Hungary: "Macarıstan",
  Iceland: "İslandiya",
  India: "Hisdistan",
  Indonesia: "İndoneziya",
  Iran: "İran",
  Iraq: "İraq",
  Ireland: "İrlandiya",
  Israel: "İsrail",
  Italy: "İtaliya",
  Jamaica: "Yamayka",
  Japan: "Yaponiya",
  Jordan: "İordaniya",
  Kazakhstan: "Qazaxıstan",
  Kenya: "Kenya",
  Kiribati: "Kiribati",
  KoreaNorth: "Şimali Koreya",
  KoreaSouth: "Cənubi Koreya",
  Kuwait: "Küveyt",
  Kyrgyzstan: "Qırğızıstan",
  Laos: "Laos",
  Latvia: "Latviya",
  Lebanon: "Livan",
  Lesotho: "Lesoto",
  Liberia: "Liberiya",
  Libya: "Liviya",
  Liechtenstein: "Lixtenşteyn",
  Lithuania: "Litva",
  Luxembourg: "Lüksemburq",
  Madagascar: "Madaqaskar",
  Malawi: "Malavi",
  Malaysia: "Malayziya",
  Maldives: "Maldiv adaları",
  Mali: "Mali",
  Malta: "Malta",
  MarshallIslands: "Marşal Adaları",
  Mauritania: "Mavritaniya",
  Mauritius: "Mavrikiy",
  Mexico: "Meksika",
  Micronesia: "Mikroneziya",
  Moldova: "Moldova",
  Monaco: "Monako",
  Mongolia: "Monqolustan",
  Montenegro: "Monteneqro",
  Morocco: "Mərakeş",
  Mozambique: "Mozambik",
  Myanmar: "Myanmar",
  Namibia: "Namibiya",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Netherlands: "Hollandiya",
  NewZealand: "Yeni Zelandiya",
  Nicaragua: "Nikaraqua",
  Niger: "Niger",
  Nigeria: "Nigeriya",
  NorthMacedonia: "Şimali Makedoniya",
  Norway: "Norveç",
  Oman: "Oman",
  Pakistan: "Pakistan",
  Palau: "Palau",
  Panama: "Panama",
  PapuaNewGuinea: "Papua Yeni Qvineya",
  Paraguay: "Paraqvay",
  Peru: "Peru",
  Philippines: "Filippin",
  Poland: "Polşa",
  Portugal: "Portuqaliya",
  Qatar: "Qətər",
  Romania: "Rumıniya",
  Russia: "Rusiya",
  Rwanda: "Ruanda",
  SaintKittsandNevis: "Müqəddəs Kitts və Nevis",
  SaintLucia: "Müqəddəs Lucia",
  SaintVincentAndTheGrenadines: "Müqəddəs Vinsent və Qrenadinlər",
  Samoa: "Samoa",
  SanMarino: "San Marino",
  SaoTomeandPrincipe: "Sao Tome və Prinsipi",
  SaudiArabia: "Səudiyyə Ərəbistanı",
  Senegal: "Seneqal",
  Serbia: "Serbiya",
  Seychelles: "Seyşel adaları",
  SierraLeone: "Sierra Leone",
  Singapore: "Sinqapur",
  Slovakia: "Slovakiya",
  Slovenia: "Sloveniya",
  SolomonIslands: "Solomon Adaları",
  Somalia: "Somali",
  SouthAfrica: "Cənubi Afrika",
  SouthSudan: "Cənubi Sudan",
  Spain: "İspaniya",
  SriLanka: "Şri Lanka",
  Sudan: "Sudan",
  Suriname: "Surinam",
  Sweden: "İsveç",
  Switzerland: "İsveçrə",
  Syria: "Suriya",
  Taiwan: "Tayvan",
  Tajikistan: "Tacikistan",
  Tanzania: "Tanzaniya",
  Thailand: "Tayland",
  TimorLeste: "Timor-Leste",
  Togo: "Toqo",
  Tonga: "Tonqa",
  TrinidadAndTobago: "Trinidad və Tobaqo",
  Tunisia: "Tunis",
  Turkey: "Türkiyə",
  Turkmenistan: "Türkmənistan",
  Tuvalu: "Tuvalu",
  Uganda: "Uqanda",
  Ukraine: "Ukrayna",
  UnitedArabEmirates: "Birləşmiş Ərəb Əmirlikləri",
  UnitedKingdom: "Birləşmiş Krallıq",
  UnitedStates: "Amerika Birləşmiş Ştatları",
  Uruguay: "Uruqvay",
  Uzbekistan: "Özbəkistan",
  Vanuatu: "Vanuatu",
  VaticanCity: "Vatikan şəhəri",
  Venezuela: "Venesuela",
  Vietnam: "Vyetnam",
  Yemen: "Yemən",
  Zambia: "Zambiya",
  Zimbabwe: "Zimbabve",
  ACCOUNT: "HESAB",
  updateProfile: "Profili Yenilə",
  updateNameSurnameCountry: "Adı, soyadı və ölkəni yenilə",
  changeEmail: "Email Ünvanını Dəyiş",
  changePassword: "Parolu Dəyiş",
  lastPasswordChanges: "Son dəyişmə 1 il əvvəl",
  OTHER: "DİGƏR",
  Notification: "Bildiriş",
  FAQ: "FAQ",
  MFAQ: "Tez-tez verilən suallar",
  updateYourProfile: "Profilini yenilə",
  Surname: "Soyad",
  changeYourName: "Adını dəyiş",
  changeYourSurname: "Soyadını dəyiş",
  selectYourCountry: "Ölkəni seç",
  saveChanges: "Dəyişiklikləri yadda saxla",
  updateYourEmail: "Email ünvanını yenilə",
  oldEmail: "Köhnə Email Ünvanı",
  enterOldEmail: "Köhnə email ünvanını daxil et",
  newEmail: "Yeni Email Ünvanı",
  enterNewEmail: "Yeni email ünvanını daxil et",
  changeYourPassword: "Parolunu dəyiş",
  oldPassword: "Köhnə parol",
  newPassword: "Yeni parol",
  confirmPassword: "Parolun təsdiqi",
  enterOldPassword: "Köhnə parolu daxil et",
  enterNewPassword: "Yeni parolu daxil et",
  confirmYourNewPassword: "Yeni parolu təsdiq et",
  helpAndSupport: "Kəmək və Dəstək",
  askQuestion: "Sual ver",
  intro: "GİRİŞ",
  createAndTekeQuiz: "KUİZ YARAT VƏ İŞTİRAK ET",
  introToQueezyApps: "Queezy app-na giriş",
  howToLoginOrSignUp: "Giriş və qeydiyyat necə edilir?",
  howToCreateQuizInApp: "App-da kuiz necə yaradılır?",
  howToTakeQuizInApp: "App-da kuizlərdə necə iştirak edilir?",
  howDoPlayWithOthers: "Digər oyunçularla necə kuiz oynaya bilərəm?",
  canIinviteMyFriends:
    "Dostlarımı birlikdə kuiz oynamaq üçün necə dəvət edə bilərəm?",
  detailQuiz: "Kuiz təfərrüatı",
  questions: "sual",
  description: "AÇIQLAMA",
  Creator: "Tərtibatçı",
  Back: "Geriyə",
  Play: "Oynat",
  suggestForYou: "Məsləhət olunanlar",
  endQuiz: "Kuizi Bitir",
  Next: "Növbəti",
  timeRemaining: "Qalan vaxt",
  true: "Doğru",
  false: "Yalnış",
  pleaseAnswerSoundedQuestion: "Səslənən suala cavab veriniz.",
  writeYourAnswer: "Cavabı yazınız.",
  mediaRecorderNotSupport: "Səs yazan sizin brovserdə dəstəklənmir.",
  getMicrophone: "Mikrofonu hazırla",
  startRecording: "Səsyazmaya başla",
  stopRecording: "Səsyazmanı dayandır",
  downloadRecording: "Səsyazmanı endir",
  goodJob: "Afərin!",
  youWillDoNextTime: "Növbəti dəfə bacaracaqsan!",
  youGet: "Sizin nəticəniz",
  checkCorrectAnswers: "Düzgün cavabları yoxla",
  completion: "TAMAMLANMA",
  skipped: "CAVABLANMAYAN",
  correctAnswers: "DÜZGÜN CAVABLAR",
  incorrectAnswers: "SƏHV CAVABLAR",
  share: "Paylaş",
  done: "Bitir",
  reviewAnswers: "Cavabların icmalı",
  QUIZNAME: "KUİZ ADI",
  yourGainedPoinst: "Sizin qazandığınız xallar",
  submit: "Bitir",
  Profile: "Profil",
  Points: "Xal",
  worldRank: "Dünya Sıralaması",
  localRank: "Yerli Sıralama",
  executeQuiz: "İcraedilən Kuiz",
  failedTest: "Uğursuz Kuiz",
  Badge: "Nişan",
  Stats: "Statistika",
  Details: "Təfərrüatlar",
  knowledgeNavigator: "Bilik Navigatoru",
  badgeCollector: "Nişan Toplayıcısı",
  queenOfQuizzes: "Kuizlər Kraliçası",
  quizWarrior: "Quiz Döyüşçüsü",
  learningLuminary: "Təhsil İşığı",
  curiosityConnoisseur: "Maraq Bilicisi",
  quizCreated: "Kuiz Hazırlanıb",
  quizWon: "Quiz Qazanılıb",
  topPerformanceByCategory: "Kateqoriyaya Görə Top Performans",
  questionsAswered: "Suallara cavab verilib",
  quizPlayed: "Kuiz Oynanılıb",
  Montly: "Aylıq",
  Annual: "İllik",
  addCoverImage: "Üzlük Şəkli Əlavə Et",
  Title: "Başlıq",
  enterQuizTitle: "Başlıq əlavə et",
  quizCategory: "Kuiz Kateqoriyası",
  chooseQuizCategory: "Kuiz kateqoriyası əlavə et",
  Description: "Açıqlama",
  enterQuizDescription: "Kuiz açıqlaması əlavə et",
  nextStep: "Növbəti addım",
  addNewCategory: "Yeni Kateqoriiya Əlavə Et",
  coverImageAdded: "Üzlük Şəkli Əlavə Edildi",
  enterNewCategory: "Yeni Kateqoriyanı Daxil Et",
  setQuestion: "Sualı təyin et",
  Continue: "Davam et",
  quizSettings: "Kuiz Tənzimləmələri",
  addNewQuestion: "Yeni Sual Əlavə Et",
  Sec: "San",
  multipleAnswer: "Çox seçimli",
  typeAnswer: "Yazılı cavablı",
  voiceAnswer: "Səsli cavablı",
  voiceQuestion: "Səsli sual",
  Checkbox: "Çekboks",
  Poll: "Sorğu",
  Puzzle: "Tapmaca",
  addQuestion: "Sual Əlavə Et",
  enterYourQuestion: "Sualını daxil et",
  addExplanation: "Açıqlama Əlavə Et",
  enterExplanationToQuestion: "Suala açıqlama daxil et",
  addCorectOption: "Doğru Seçimi Əlavə Et",
  enterCorectOption: "Doğru seçimi daxil et",
  enterWrongOption: "Yanlış seçimi daxil et",
  addWrongOption: "Yanlış Seçimi Əlavə Et",
  addTrueOption: "Doğru Seçimi Əlavə Et",
  enterTrueOption: "Doğru seçimi daxil et",
  addAnswers: "Cavabları Əlavə Et",
  addAnswer: "Cavab Əlavə Et",
  enterYourAnswer: "Cavabını daxil et",
  addVoiceAnswer: "Səsli Cavab Əlavə Et",
  enterOption: "Seçim daxil et",
  trueOrFalse: "Doğru yoxsa Yalnış",
  Question: "Sual",
  addAudioFile: "Audio Fayl Əlavə Et",
  fileSelected: "Fayl Seçildi",
  quizInformation: "Kuiz Məlumatı",
  Save: "Yadda saxla",
};

const eng = {
  dashboard: "Dashboard",
  discover: "Discover",
  leaderboard: "Leaderboard",
  settings: "Settings",
  quizLibrary: "Quiz Library",
  quizPerformance: "Quiz Performance",
  recentQuiz: "Recent Quiz",
  ongoingQuiz: "Ongoing Quiz",
  seeAll: "See all",
  seeLess: "See less",
  weekly: "Weekly",
  allTime: "All Time",
  other: "Other",
  lastAddedQuizzes: "Last Added Quizzes",
  friends: "Friends",
  point: "P",
  quizzes: "Quizzes",
  goodMorning: "GOOD MORNING",
  goodAfternoon: "GOOD AFTERNOON",
  goodEvening: "GOOD EVENING",
  goodNigth: "GOOD NIGHT",
  Categories: "Categories",
  Quiz: "Quiz",
  ClearAll: "Clear All",
  RecentSearchers: "Recent Searches",
  QuizAndCategories: "Quiz and categoriess",
  myAccount: "My Account",
  logOut: "Logout",
  liveQuizText: " There are currently no live quizzes.",
  liveQuiz: "Live Quiz",
  quizList: "Quiz List",
  createQuiz: "Create Quiz",
  findQuizzes: "Find quizzes by name",
  Category: "Category",
  points: "points",
  Name: "Name",
  Country: "Country",
  Rank: "Rank",
  Afghanistan: "Afghanistan",
  Albania: "Albania",
  Algeria: "Algeria",
  Andorra: "Andorra",
  Angola: "Angola",
  AntiguaAndBarbuda: "Antigua and Barbuda",
  Argentina: "Argentina",
  Armenia: "Armenia",
  Australia: "Australia",
  Austria: "Austria",
  Azerbaijan: "Azerbaijan",
  Bahamas: "Bahamas",
  Bahrain: "Bahrain",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  Belarus: "Belarus",
  Belgium: "Belgium",
  Belize: "Belize",
  Benin: "Benin",
  Bhutan: "Bhutan",
  Bolivia: "Bolivia",
  BosniaAndHerzegovina: "Bosnia and Herzegovina",
  Botswana: "Botswana",
  Brazil: "Brazil",
  Brunei: "Brunei",
  Bulgaria: "Bulgaria",
  BurkinaFaso: "Burkina Faso",
  Burundi: "Burundi",
  CaboVerde: "Cabo Verde",
  Cambodia: "Cambodia",
  Cameroon: "Cameroon",
  Canada: "Canada",
  CentralAfricanRepublic: "Central African Republic",
  Chad: "Chad",
  Chile: "Chile",
  China: "China",
  Colombia: "Colombia",
  Comoros: "Comoros",
  Congo: "Congo",
  CostaRica: "Costa Rica",
  CotedIvoire: "Côte d'Ivoire",
  Croatia: "Croatia",
  Cuba: "Cuba",
  Cyprus: "Cyprus",
  CzechRepublic: "Czech Republic",
  Denmark: "Denmark",
  Djibouti: "Djibouti",
  Dominica: "Dominica",
  DominicanRepublic: "Dominican Republic",
  Ecuador: "Ecuador",
  Egypt: "Egypt",
  ElSalvador: "El Salvador",
  EquatorialGuinea: "Equatorial Guinea",
  Eritrea: "Eritrea",
  Estonia: "Estonia",
  Eswatini: "Eswatini",
  Ethiopia: "Ethiopia",
  Fiji: "Fiji",
  Finland: "Finland",
  France: "France",
  Gabon: "Gabon",
  Gambia: "Gambia",
  Georgia: "Georgia",
  Germany: "Germany",
  Ghana: "Ghana",
  Greece: "Greece",
  Grenada: "Grenada",
  Guatemala: "Guatemala",
  Guinea: "Guinea",
  GuineaBissau: "Guinea-Bissau",
  Guyana: "Guyana",
  Haiti: "Haiti",
  Honduras: "Honduras",
  Hungary: "Hungary",
  Iceland: "Iceland",
  India: "India",
  Indonesia: "Indonesia",
  Iran: "Iran",
  Iraq: "Iraq",
  Ireland: "Ireland",
  Israel: "Israel",
  Italy: "Italy",
  Jamaica: "Jamaica",
  Japan: "Japan",
  Jordan: "Jordan",
  Kazakhstan: "Kazakhstan",
  Kenya: "Kenya",
  Kiribati: "Kiribati",
  KoreaNorth: "Korea, North",
  KoreaSouth: "Korea, South",
  Kuwait: "Kuwait",
  Kyrgyzstan: "Kyrgyzstan",
  Laos: "Laos",
  Latvia: "Latvia",
  Lebanon: "Lebanon",
  Lesotho: "Lesotho",
  Liberia: "Liberia",
  Libya: "Libya",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lithuania",
  Luxembourg: "Luxembourg",
  Madagascar: "Madagascar",
  Malawi: "Malawi",
  Malaysia: "Malaysia",
  Maldives: "Maldives",
  Mali: "Mali",
  Malta: "Malta",
  MarshallIslands: "Marshall Islands",
  Mauritania: "Mauritania",
  Mauritius: "Mauritius",
  Mexico: "Mexico",
  Micronesia: "Micronesia",
  Moldova: "Moldova",
  Monaco: "Monaco",
  Mongolia: "Mongolia",
  Montenegro: "Montenegro",
  Morocco: "Morocco",
  Mozambique: "Mozambique",
  Myanmar: "Myanmar",
  Namibia: "Namibia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Netherlands: "Netherlands",
  NewZealand: "New Zealand",
  Nicaragua: "Nicaragua",
  Niger: "Niger",
  Nigeria: "Nigeria",
  NorthMacedonia: "North Macedonia",
  Norway: "Norway",
  Oman: "Oman",
  Pakistan: "Pakistan",
  Palau: "Palau",
  Panama: "Panama",
  PapuaNewGuinea: "Papua New Guinea",
  Paraguay: "Paraguay",
  Peru: "Peru",
  Philippines: "Philippines",
  Poland: "Poland",
  Portugal: "Portugal",
  Qatar: "Qatar",
  Romania: "Romania",
  Russia: "Russia",
  Rwanda: "Rwanda",
  SaintKittsandNevis: "Saint Kitts and Nevis",
  SaintLucia: "Saint Lucia",
  SaintVincentAndTheGrenadines: "Saint Vincent and the Grenadines",
  Samoa: "Samoa",
  SanMarino: "San Marino",
  SaoTomeandPrincipe: "Sao Tome and Principe",
  SaudiArabia: "Saudi Arabia",
  Senegal: "Senegal",
  Serbia: "Serbia",
  Seychelles: "Seychelles",
  SierraLeone: "Sierra Leone",
  Singapore: "Singapore",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  SolomonIslands: "Solomon Islands",
  Somalia: "Somalia",
  SouthAfrica: "South Africa",
  SouthSudan: "South Sudan",
  Spain: "Spain",
  SriLanka: "Sri Lanka",
  Sudan: "Sudan",
  Suriname: "Suriname",
  Sweden: "Sweden",
  Switzerland: "Switzerland",
  Syria: "Syria",
  Taiwan: "Taiwan",
  Tajikistan: "Tajikistan",
  Tanzania: "Tanzania",
  Thailand: "Thailand",
  TimorLeste: "Timor-Leste",
  Togo: "Togo",
  Tonga: "Tonga",
  TrinidadAndTobago: "Trinidad and Tobago",
  Tunisia: "Tunisia",
  Turkey: "Turkey",
  Turkmenistan: "Turkmenistan",
  Tuvalu: "Tuvalu",
  Uganda: "Uganda",
  Ukraine: "Ukraine",
  UnitedArabEmirates: "United Arab Emirates",
  UnitedKingdom: "United Kingdom",
  UnitedStates: "United States",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistan",
  Vanuatu: "Vanuatu",
  VaticanCity: "Vatican City",
  Venezuela: "Venezuela",
  Vietnam: "Vietnam",
  Yemen: "Yemen",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabwe",
  ACCOUNT: "ACCOUNT",
  updateProfile: "Update Profile",
  updateNameSurnameCountry: "Update name, surname and country",
  changeEmail: "Change Email Address",
  changePassword: "Change Password",
  lastPasswordChanges: "Last change 1 year ago",
  OTHER: "OTHER",
  Notification: "Notification",
  FAQ: "FAQ",
  MFAQ: "Most frequently asked questions",
  updateYourProfile: "Update your profile",
  Surname: "Surname",
  changeYourName: "Change your name",
  changeYourSurname: "Change your surname",
  selectYourCountry: "Select your country",
  saveChanges: "Save changes",
  updateYourEmail: "Update your email address",
  oldEmail: "Old Email Address",
  enterOldEmail: "Enter old email address",
  newEmail: "New Email Address",
  enterNewEmail: "Enter new email address",
  changeYourPassword: "Change your password",
  oldPassword: "Old password",
  newPassword: "New password",
  confirmPassword: "Confirm password",
  enterOldPassword: "Enter your old password",
  enterNewPassword: "Enter your new password",
  confirmYourNewPassword: "Confirm your new password",
  helpAndSupport: "Help and Support",
  askQuestion: "Ask questions",
  intro: "INTRO",
  createAndTekeQuiz: "CREATE AND TAKE QUIZ",
  introToQueezyApps: "Intro to Queezy apps",
  howToLoginOrSignUp: "How to login or sign up?",
  howToCreateQuizInApp: "How to create quiz in the app?",
  howToTakeQuizInApp: "How to take quiz in the app?",
  howDoPlayWithOthers: "How do i play quiz with other players?",
  canIinviteMyFriends: "Can i invite my friends to play quiz together?",
  detailQuiz: "Detail Quiz",
  questions: "questions",
  description: "description",
  Creator: "Creator",
  Back: "Back",
  Play: "Play",
  suggestForYou: "Suggest for you",
  endQuiz: "End Quiz",
  Next: "Next",
  timeRemaining: "Time Remaining",
  true: "True",
  false: "False",
  pleaseAnswerSoundedQuestion: "Please answer sounded question.",
  writeYourAnswer: "Write your answer",
  mediaRecorderNotSupport:
    "The MediaRecorder API is not supported in your browser.",
  getMicrophone: "Get Microphone",
  startRecording: "Start Recording",
  stopRecording: "Stop Recording",
  downloadRecording: "Download Recording",
  goodJob: "Good job!",
  youWillDoNextTime: "You will do next time!",
  youGet: "You get",
  checkCorrectAnswers: "Check Correct Answer",
  completion: "COMPLETION",
  skipped: "SKIPPED",
  correctAnswers: "CORRECT ANSWERS",
  incorrectAnswers: "INCORRECT ANSWERS",
  share: "Share",
  done: "Done",
  reviewAnswers: "Review Answers",
  QUIZNAME: "QUIZ NAME",
  yourGainedPoinst: "Your Gained Points",
  submit: "Submit",
  Profile: "Profile",
  Points: "Points",
  worldRank: "World Rank",
  localRank: "Local Rank",
  executeQuiz: "Execute Quiz",
  failedTest: "Failed Test",
  Badge: "Badge",
  Stats: "Stats",
  Details: "Details",
  knowledgeNavigator: "Knowledge Navigator",
  badgeCollector: "Badge Collector",
  queenOfQuizzes: "Queen Of Quizzes",
  quizWarrior: "Quiz Warrior",
  learningLuminary: "Learning Luminary",
  curiosityConnoisseur: "Curiosity Connoisseur",
  quizCreated: "Quiz Created",
  quizWon: "Quiz Won",
  topPerformanceByCategory: "Top performance by category",
  questionsAswered: "Questions Answered",
  quizPlayed: "Quiz Played",
  Montly: "Montly",
  Annual: "Annual",
  addCoverImage: "Add Cover Image",
  Title: "Title",
  enterQuizTitle: "Enter quiz title",
  quizCategory: "Quiz Category",
  chooseQuizCategory: "Choose quiz category",
  Description: "Description",
  enterQuizDescription: "Enter quiz description",
  nextStep: "Next Step",
  addNewCategory: "Add New Category",
  enterNewCategory: "Enter New Category",
  coverImageAdded: "Cover Image Added",
  setQuestion: "Set Question",
  Continue: "Continue",
  quizSettings: "Quiz Settings",
  addNewQuestion: "Add New Question",
  Sec: "Sec",
  multipleAnswer: "Multiple Answer",
  typeAnswer: "Type Answer",
  voiceAnswer: "Voice Answer",
  voiceQuestion: "Voice Question",
  Checkbox: "Checkbox",
  Poll: "Poll",
  Puzzle: "Puzzle",
  enterYourQuestion: "Enter Your Question",
  addQuestion: "Add Question",
  addExplanation: "Add Explanation",
  enterExplanationToQuestion: "Enter explanation to question",
  addCorectOption: "Add Correct Option",
  enterCorectOption: "Enter correct option",
  addWrongOption: "Add Wrong Option",
  enterWrongOption: "Enter wrong option",
  addTrueOption: "Add True Option",
  enterTrueOption: "Enter true option",
  addAnswer: "Add Answer",
  addAnswers: "Add Answers",
  enterYourAnswer: "Enter your answer",
  addVoiceAnswer: "Enter voice answer",
  enterOption: "Enter option",
  trueOrFalse: "True or False",
  Question: "Question",
  addAudioFile: "Add Audio File",
  fileSelected: "File Selected",
  quizInformation: "Quiz Information",
  Save: "Yadda saxla",
};
export { aze, eng };
